### ISSUE TITLE
copying default properties

### ISSUE THREAD

**Issue by LeanderK** [intellimate/IzouSDK#17]
The default properties are missing. @jundl77 can you look at it?

**Comment by jundl77** [comment]
In addOns?

**Comment by LeanderK** [comment]
yes, if you add new add ons, the properties are empty

**Comment by jundl77** [comment]
Oh I did not know that, that was never intended

**Comment by jundl77** [comment]
but so nonetheless, the default property files are not copied you say?

**Comment by LeanderK** [comment]
yes

**Comment by LeanderK** [comment]
sry, 23 hours ago was 00:37 ;)

**Comment by jundl77** [comment]
Yeah I'll fix it later, talking to my family right now

**Comment by jundl77** [comment]
Ok fixed it, also I renamed the defaultProperties.txt file to default_properties.txt so please change the names of your default property files, or else it will not work

**Comment by LeanderK** [comment]
wtf, ok :)

**Comment by LeanderK** [comment]
can confirm that it works
