### ISSUE TITLE
Properties Naming

### ISSUE THREAD

**Issue by LeanderK** [intellimate/IzouSDK#9]
I don't know if this is intended, but the properties naming changed:
e.g.: leanderk.izou.wifipresence.AddOn.**PropertiesAssistant**.properties
@jundl77 maybe you can look into it, since you wrote the code

**Comment by jundl77** [comment]
Yes that is intended, remember, Assistant was supposed to be for AddOn "Managers" and Manager for izou "Manager"

**Comment by LeanderK** [comment]
but why not leanderk.izou.wifipresence.properties?

**Comment by LeanderK** [comment]
i mean whats the value of .AddOn.PropertiesAssistant

**Comment by LeanderK** [comment]
this still bothers me. I mean the files....why should they reflect that? This doesn't add much information.

**Comment by jundl77** [comment]
what do you mean? What do they reflect?

**Comment by LeanderK** [comment]
the actual file-names are leanderk.izou.wifipresence.AddOn.PropertiesAssistant.properties
why not lenders.izou.wifipresence.properties?

**Comment by LeanderK** [comment]
i mean its not that important

**Comment by jundl77** [comment]
Done with that

**Comment by LeanderK** [comment]
cool!
